"""The generated ContractAudit.h must stay byte-identical to the committed header."""

from __future__ import annotations

import difflib
import io
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(HERE / "contracts"))

from generate_observer import main as generate_main


class GeneratedHeader(unittest.TestCase):
    def test_header_only_matches_committed_bytes(self):
        """A regenerated header that differs in any byte from the committed file is a fail."""
        header = REPO / "Source" / "System" / "ContractAudit.h"
        committed = header.read_bytes()
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "ContractAudit.h"
            buf = io.StringIO()
            with redirect_stdout(buf):
                code = generate_main(["--repo", str(REPO), "--header-only", "--output", str(out)])
            self.assertEqual(code, 0, buf.getvalue())
            generated = out.read_bytes()
            if generated != committed:
                diff = "".join(difflib.unified_diff(
                    committed.decode("utf-8", "replace").splitlines(True),
                    generated.decode("utf-8", "replace").splitlines(True),
                    fromfile=str(header), tofile="generated"))
                self.fail(diff or f"{len(committed)} committed bytes differ from "
                                  f"{len(generated)} generated bytes outside the decoded text")


if __name__ == "__main__":
    unittest.main()
