pch = meson.current_source_dir()/'System/StandardIncludes.h'
sources = []
source_libs = []
source_inc_dirs += [include_directories(
  '.',
  'AI',
  'CI',
  'Activities',
  'Entities',
  'GUI',
  'GUI/Wrappers',
  'Lua',
  'Managers',
  'Menus',
  'Network',
  'Renderer',
  'System')]

subdir('AI')
subdir('CI')
subdir('Activities')
subdir('Entities')
subdir('GUI')
subdir('Lua')
subdir('Managers')
subdir('Menus')
subdir('Network')
subdir('Renderer')
subdir('System')
